In [29]:
import numpy as np

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
import time

In [32]:
a = np.random.rand(10000000)
b = np.random.rand(10000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized Time "+ str(1000*(toc-tic))+"ms")

2499635.023384959
Vectorized Time 12.613534927368164ms


In [33]:
c=0
tic = time.time()
for i in range(10000000):
  c+=a[i]*b[i]

toc = time.time()
print(c)
print("For Loop  Time "+ str(1000*(toc-tic))+"ms")

2499635.0233846945
For Loop  Time 6114.966630935669ms


In [34]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

In [35]:
A.shape

(3, 4)

In [36]:
cal = A.sum(axis=0)

In [37]:
cal

array([ 59. , 239. , 155.4,  76.9])

In [38]:
cal.shape

(4,)

In [39]:
percentage = 100*A/(cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [40]:
B = np.array([56.0,0.0,4.4,68.0])

In [41]:
B.shape

(4,)

In [42]:
B = B.reshape(4,1)

In [43]:
B

array([[56. ],
       [ 0. ],
       [ 4.4],
       [68. ]])

In [44]:
B + 100

array([[156. ],
       [100. ],
       [104.4],
       [168. ]])

In [45]:
a = np.random.randn(5)

In [46]:
print(a)

[-0.90136292 -1.08545695  1.09379628 -0.44387543 -0.88573033]


In [47]:
print(a.shape)

(5,)


This is called Rank 1 Array

In [48]:
b = a.T
print(b.shape)

(5,)


In [49]:
print(np.dot(a,a.T))

4.168605826174752


In [50]:
a = np.random.randn(5,1)

In [51]:
print(a)

[[-1.27906694]
 [ 0.20448249]
 [-0.48511108]
 [ 1.24626497]
 [-1.24491672]]


In [52]:
print(a.T)

[[-1.27906694  0.20448249 -0.48511108  1.24626497 -1.24491672]]


In [53]:
print(np.dot(a,a.T))

[[ 1.63601222 -0.26154679  0.62048954 -1.59405632  1.59233182]
 [-0.26154679  0.04181309 -0.09919672  0.25483937 -0.25456367]
 [ 0.62048954 -0.09919672  0.23533276 -0.60457695  0.6039229 ]
 [-1.59405632  0.25483937 -0.60457695  1.55317638 -1.5514961 ]
 [ 1.59233182 -0.25456367  0.6039229  -1.5514961   1.54981765]]
